export enum SkillTechnologies {
  Html5 = 'HTML5',
  CSS3 = 'CSS3',
  Javascript = 'Javascript',
  Typescript = 'Typescript',
  Angular = 'Angular +7',
  Karma = 'Karma',
  Jasmine = 'Jasmine',
  Gauge = 'Gauge',
  Taiko = 'Taiko',
  AngularPwa = 'Angular PWA',
  NgRx = 'NgRx',
  SASS = 'SASS (SCSS)',
  Flutter = 'Flutter',
  Dart = 'Dart',
  GitHub = 'GitHub',
  GitLab = 'GitLab',
}
