# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI + CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build:ci

      - name: Test
        run: npm run test:ci

  DEV:
    name: Deploy to Dev
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    needs: build_and_test
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUGMENTED_RESUME }}"
          projectId: augmented-resume

  STAGING:
    name: Deploy to Staging
    if: github.event.pull_request.merged
    need: build_and_test
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: TODO
        run: echo "run e2e tests when available (cypress)"

  PRODUCTION:
    name: Deploy to Production
    needs: STAGING
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUGMENTED_RESUME }}"
          channelId: live
          projectId: augmented-resume
