# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:ci

  TEST:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

  DEV:
    name: Deploy to Dev
    if: github.event_name == 'push'
    needs: TEST
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: TODO
        run: echo "deploy to dev"

  STAGING:
    name: Deploy to Staging
    needs: DEV
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: TODO
        run: echo "run e2e tests when available (cypress)"

  PRODUCTION:
    name: Deploy to Production
    needs: STAGING
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: TODO
        run: echo "deploy to Firebase"
